---

version: '3'
services:
  openvas:
    image: dgiorgio/openvas
    hostname: "openvas"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9390-9392:9390-9392"
    volumes:
      - "data:/var/lib/openvas/"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      deck-chores.dump.command: sh -c "update-NVT"
      deck-chores.dump.cron: 0 23 * * *
      
  cron:
    image: funkyfuture/deck-chores
    restart: always
    environment:
      TIMEZONE: America/Sao_Paulo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      
volumes:
  data:
